#!/usr/bin/env python3
"""Verify the 24-game solutions in solutions.txt and, optionally, emit the
embedded puzzle table consumed by the C++ build.

File format (tab-separated, one puzzle per line):

    <index>\t<a b c d>\t<solution>\t<solution>...

where the puzzle is four space-separated integers (1..13) and every remaining
field is a solution expression using ``+ - * /`` (``x`` is written with the
Unicode multiplication sign ``×``) and parentheses. Each solution must
evaluate to exactly 24 while using each of the four puzzle numbers exactly once.

Usage:
    verify_solutions.py [solutions.txt] [--header path/to/puzzles_generated.h]

Exits non-zero if any solution fails to verify, so it can gate the build.
"""

import sys
from fractions import Fraction


class ParseError(Exception):
    pass


def tokenize(text):
    """Turn an expression into a list of ('num', int) / ('op', char) tokens."""
    text = text.replace("×", "*").replace("÷", "/").replace("−", "-")
    tokens = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c.isspace():
            i += 1
        elif c.isdigit():
            j = i
            while j < n and text[j].isdigit():
                j += 1
            tokens.append(("num", int(text[i:j])))
            i = j
        elif c in "+-*/()":
            tokens.append((c, None))
            i += 1
        else:
            raise ParseError(f"unexpected character {c!r}")
    return tokens


class Parser:
    """Recursive-descent parser producing an exact Fraction.

    grammar:
        expr   := term (('+' | '-') term)*
        term   := factor (('*' | '/') factor)*
        factor := NUMBER | '(' expr ')' | ('+' | '-') factor
    """

    def __init__(self, tokens):
        self.tokens = tokens
        self.pos = 0
        self.literals = []  # every integer literal encountered, in order

    def _peek(self):
        return self.tokens[self.pos][0] if self.pos < len(self.tokens) else None

    def _advance(self):
        tok = self.tokens[self.pos]
        self.pos += 1
        return tok

    def parse(self):
        value = self._expr()
        if self.pos != len(self.tokens):
            raise ParseError("trailing tokens")
        return value

    def _expr(self):
        value = self._term()
        while self._peek() in ("+", "-"):
            op = self._advance()[0]
            rhs = self._term()
            value = value + rhs if op == "+" else value - rhs
        return value

    def _term(self):
        value = self._factor()
        while self._peek() in ("*", "/"):
            op = self._advance()[0]
            rhs = self._factor()
            if op == "*":
                value = value * rhs
            else:
                if rhs == 0:
                    raise ParseError("division by zero")
                value = value / rhs
        return value

    def _factor(self):
        tok = self._peek()
        if tok == "num":
            value = self._advance()[1]
            self.literals.append(value)
            return Fraction(value)
        if tok == "(":
            self._advance()
            value = self._expr()
            if self._peek() != ")":
                raise ParseError("expected ')'")
            self._advance()
            return value
        if tok == "-":
            self._advance()
            return -self._factor()
        if tok == "+":
            self._advance()
            return self._factor()
        raise ParseError(f"unexpected token {tok!r}")


def evaluate(expression):
    parser = Parser(tokenize(expression))
    return parser.parse(), parser.literals


def emit_header(path, puzzles):
    lines = [
        "// Generated by tools/verify_solutions.py from solutions.txt -- do not edit.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace tf {",
        f"inline constexpr int kPuzzleCount = {len(puzzles)};",
        "inline constexpr uint8_t kPuzzles[kPuzzleCount][4] = {",
    ]
    lines += ["    {%d, %d, %d, %d}," % tuple(p) for p in puzzles]
    lines += ["};", "}  // namespace tf", ""]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main(argv):
    path = "solutions.txt"
    header = None
    rest = []
    i = 1
    while i < len(argv):
        if argv[i] == "--header":
            header = argv[i + 1]
            i += 2
        else:
            rest.append(argv[i])
            i += 1
    if rest:
        path = rest[0]

    puzzles = []
    solutions_checked = 0
    failures = []

    with open(path, encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.rstrip("\n")
            if not line.strip():
                continue
            parts = line.split("\t")
            if len(parts) < 3:
                failures.append((lineno, line.strip()[:40], "fewer than 3 fields"))
                continue
            try:
                numbers = [int(x) for x in parts[1].split()]
            except ValueError:
                failures.append((lineno, parts[1].strip(), "non-integer in puzzle"))
                continue
            if len(numbers) != 4:
                failures.append((lineno, parts[1].strip(), f"expected 4 numbers, got {len(numbers)}"))
                continue
            puzzles.append(numbers)
            expected = sorted(numbers)
            for solution in parts[2:]:
                solution = solution.strip()
                if not solution:
                    continue
                solutions_checked += 1
                try:
                    value, literals = evaluate(solution)
                except ParseError as exc:
                    failures.append((lineno, solution, f"parse error: {exc}"))
                    continue
                if value != 24:
                    failures.append((lineno, solution, f"evaluates to {value}, not 24"))
                elif sorted(literals) != expected:
                    failures.append((lineno, solution, f"uses {sorted(literals)}, puzzle is {expected}"))

    print(f"puzzles: {len(puzzles)}   solutions checked: {solutions_checked}   failures: {len(failures)}")
    for lineno, solution, message in failures[:50]:
        print(f"  line {lineno}: {solution!r}: {message}")
    if len(failures) > 50:
        print(f"  ... and {len(failures) - 50} more")

    if header is not None and not failures:
        emit_header(header, puzzles)
        print(f"wrote {header} ({len(puzzles)} puzzles)")

    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
